# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VERO' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VERO
pod 'IQKeyboardManager'
pod 'SDWebImage/WebP'
pod 'ObjectMapper', '~> 3.1'

  target 'VEROTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VEROUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
